title: Miraz Zaidi 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Software developer Generalist - 
  <br><br>
  Expertise in C++, Python - Windows Desktop/Console Applications - Embedded Applications  
  <br><br>
  <a href="https://www.linkedin.com/in/mirazzaidi/">View My LinkedIn Profile</a> 
theme: jekyll-theme-cayman
google_analytics: UA-117515839-1
