title: Miraz Zaidi # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software developer Generalist - 
  <br><br>
  Expertise in C++, Python - Windows Desktop/Console Applications - Embedded Applications  
  <br><br>
  <a href="https://www.linkedin.com/in/mirazzaidi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
