title: Miraz Zaidi 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Software developer Generalist - 
  <br><br>
  Expertise in C++, Python - Windows Desktop/Console Applications - Embedded Applications  
  <br><br>
  <a href="https://www.linkedin.com/in/mirazzaidi/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://drive.google.com/open?id=1pJJmME6B1z7fJZBabXXTi7OTRf7Of3QB">View My Resume</a> 

theme: jekyll-theme-minimal
google_analytics: UA-117515839-1
